# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: langbot/common/common.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1blangbot/common/common.proto\x12\x0elangbot.common\"\x10\n\x0eGenericRequest\"J\n\x0fGenericResponse\x12&\n\x06status\x18\x01 \x01(\x0e\x32\x16.langbot.common.Status\x12\x0f\n\x07message\x18\x02 \x01(\t*5\n\x06Status\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x06\n\x02OK\x10\x01\x12\t\n\x05\x45RROR\x10\x02\x12\x0b\n\x07WARNING\x10\x03\x62\x06proto3')

_STATUS = DESCRIPTOR.enum_types_by_name['Status']
Status = enum_type_wrapper.EnumTypeWrapper(_STATUS)
UNKNOWN = 0
OK = 1
ERROR = 2
WARNING = 3


_GENERICREQUEST = DESCRIPTOR.message_types_by_name['GenericRequest']
_GENERICRESPONSE = DESCRIPTOR.message_types_by_name['GenericResponse']
GenericRequest = _reflection.GeneratedProtocolMessageType('GenericRequest', (_message.Message,), {
  'DESCRIPTOR' : _GENERICREQUEST,
  '__module__' : 'langbot.common.common_pb2'
  # @@protoc_insertion_point(class_scope:langbot.common.GenericRequest)
  })
_sym_db.RegisterMessage(GenericRequest)

GenericResponse = _reflection.GeneratedProtocolMessageType('GenericResponse', (_message.Message,), {
  'DESCRIPTOR' : _GENERICRESPONSE,
  '__module__' : 'langbot.common.common_pb2'
  # @@protoc_insertion_point(class_scope:langbot.common.GenericResponse)
  })
_sym_db.RegisterMessage(GenericResponse)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STATUS._serialized_start=141
  _STATUS._serialized_end=194
  _GENERICREQUEST._serialized_start=47
  _GENERICREQUEST._serialized_end=63
  _GENERICRESPONSE._serialized_start=65
  _GENERICRESPONSE._serialized_end=139
# @@protoc_insertion_point(module_scope)
