# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: langbot/common/micro/api/app.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from langbot.common import common_pb2 as langbot_dot_common_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"langbot/common/micro/api/app.proto\x12\x18langbot.common.micro.api\x1a\x1blangbot/common/common.proto2X\n\nAppManager\x12J\n\x05Hello\x12\x1e.langbot.common.GenericRequest\x1a\x1f.langbot.common.GenericResponse\"\x00\x62\x06proto3')



_APPMANAGER = DESCRIPTOR.services_by_name['AppManager']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _APPMANAGER._serialized_start=93
  _APPMANAGER._serialized_end=181
# @@protoc_insertion_point(module_scope)
